### PR TITLE
Add_CN_web_translation

### PR DESCRIPTION
**Pull request by Biniou180**
Hi David,
Since long time ago, I said to myself I'll translate the web site to Chinese and finally I did it, with few years delay...
I took the chance that you won't publish new episode this month (because your cat generator which I adore! ) and my maternity leave (so full time at home before my baby arrives) to do it, and now it's done. I hope that will bring more chinese readers to the site.
Sur ce, je te souhaite un très bon mois de décembre, joyeux noël, bonne année et tout et tout :)
- Ran

### CODE REVIEW

**Comment by Deevad** [comment]
Hi Ran! A big thank you for this big present ! I'll merge it in the next hour for sure. 
You and Pyves will have a baby? What a cool news! I hope a lot of happiness and calm in this last period fulltime at home for you. 

Je reviens très vite avec un episode 20 (muet) ;-) Merci!

**Comment by Deevad** [comment]
Ha, question:

The file is in **zh** iso language. While translation in Chinese on the website are in **cn** .
Can I move it to also use **cn** ?

**Comment by Deevad** [comment]
From IRC: 

**18:24CalimeroTeknik:**
zh_CN is simplified Chinese and zh_TW is traditional (used in Taiwan)
this looks like simplified, so it's OK to use cn
however you'll have a problem if you have a traditional Chinese translation, because tw is Twi (an African language with millions of speakers) and that would collide
zh-t and zh-s are the ISO639 answer
well that was ISO639-2, the shortest one; the first standard, and used in web pages to say which language they are in, is zh-Hant and zh-Hans http://www.w3schools.com/tags/ref_language_codes.asp
**18:34 deevad:**
thank you for the in-depht explanation. I'll move to 'cn' in a first time. If more work on a second traditionnal/simplified chinese appears, I'll figure a more complex solution
**18:34 CalimeroTeknik:**
'cn' is not a standard, it's just OK to use in URLs

I'm taking care of moving it :)

**Comment by Deevad** [comment]
It's online :)
http://www.peppercarrot.com/cn/ 
Congratulation, the file was perfect to launch. Feel free to keep doing modification on it,  the php file is not really WYSIWYG

**Comment by Biniou180** [comment]
Great!
[Pyves here ;-) ]
Thanks to CalimeroTeknik for the answer, we didn't have any clue of the correct code to use in chinese (Ran know zh and cn, and she confirms it's simplified chinese, not traditional, but all this ISO stuff... 😅 )

...Also, we already plan to read pepper & carrot stories to our future little witch (she will be delivered around Xmas \o/), when she will be old enough to understand... and it will be a good way to practice both chinese and french :-D

**Pull request merged**
