### PR TITLE
Translated the website to Hungarian.

### PR DESCRIPTION
**Pull request by hgabor**
I hope I didn't make any typos :), I couldn't check the site live.

### CODE REVIEW

**Comment by Deevad** [comment]
Wow, thank you about this big one !
http://www.peppercarrot.com/hu/static3/webcomics
I just pushed it online; the "google font" I use to style the page has missing glyph unfortunately. 
I'll try to do an exception rule for [hu] and find another font , or see if the font on GoogleFont can get 'Latin extended' pack. 

Feel free to check live, and propose fix for mistakes, or line breaks , etc... I'll add you to the collaborator of this repository so you can do/push changes directly with github online editor.

**Comment by Deevad** [comment]
Ok, updated :)
I found a good font with handwrited effect and all glyph for online : 
http://www.peppercarrot.com/hu/static3/webcomics
https://www.google.com/fonts#QuickUsePlace:quickUse/Family:Shadows+Into+Light+Two/Script:latin-ext
I'll try to find a way in a near future to host myself the 'online' font, and change it as I do with the 'Lavi' font of Pepper&Carrot. Thanks a lot again for your work !

**Comment by hgabor** [comment]
No problem.
And thanks for giving me push access, I already see a few things I'll need to fix  :)

**Comment by Deevad** [comment]
You're welcome :)
Thanks for contributing to Pepper&Carrot

**Pull request merged**
