### PR TITLE
Initial breton translation

### PR DESCRIPTION
**Pull request by tornoz**

### CODE REVIEW

**Comment by Deevad** [comment]
Megaclasse :) Thank you!

**Comment by Deevad** [comment]
Merci Stefan!
http://www.peppercarrot.com/br/static3/webcomics
It's online, and perfectly fit the website. Feel free to review, and bring other modification. Thank you also for directly making a 'pull request' on Github. It really ease maintaining on my side.
( I keep writing in english, because other contributor follow Github's comments )

**Comment by tornoz** [comment]
Thanks ! (I'm Gwenn, Stefan is the one translating the comics and helping me for the website translation)
I just noticed an ugly last-minute typo on the homepage so I'm sending another pull request.
I'm a developer so making pull requests is easy for me, but not so much for Stefan.

**Comment by Deevad** [comment]
@tornoz  Correction : Merci Gwenn !   ;-)   Do you want the direct access to the repository ? So you can directly push change ? I can fix this in a minute.

**Comment by tornoz** [comment]
If that's not a problem then it would be easier to correct that kind of small mistakes.

**Pull request merged**
