### PR TITLE
added initial german translation (must be proofread by another german sp...

### PR DESCRIPTION
**Pull request by torpak**
...eaker)
I tried my best to reproduce the intention of the original, as i understood it, but there were some parts where i was unsure. Also my spelling is really bad!

### CODE REVIEW

**Comment by Deevad** [comment]
Thank you @torpak ! Translating the website is a very big piece of work. I really had difficulties to make the french version. I pushed it, and I'll update it on the website in the next hour.

About proofreading, I will contact Alexandra Jordan and Helmar Suschka ( I don't know if on github I can quote his nickname; let's try: @phellmes ).  They did together all german translation for the webcomic episode.

**Comment by Deevad** [comment]
Now, it's online: http://www.peppercarrot.com/de/static2/philosophy  :)
Thank you again.

**Comment by Deevad** [comment]
An update for this pull-request thread : 
@jmf today made a proofreading commit: https://github.com/Deevad/peppercarrot_website_translation/pull/4  , It's already online. Thank you!

**Comment by phellmes** [comment]
@Deevad Thanks for tagging - it worked and got me a notification about this thread. I only had time to scan over the page quickly yesterday. Since there's the initial commit and a correction already I think I'll stay out of the website translation and keep focused on the episodes for now.

**Comment by Deevad** [comment]
@phellmes thank you for the feedback :)

**Pull request merged**
